export const kpis = [
    {
        label: "Active Stockouts",
        value: "4",
        sub: "stores affected",
        trend: "+2 since yesterday",
        dir: "up",
        bad: true,
        color: "text-destructive",
        bg: "bg-destructive/10",
        clickable: true,
        history: [
            { name: "Mon", value: 1 },
            { name: "Tue", value: 1 },
            { name: "Wed", value: 2 },
            { name: "Thu", value: 2 },
            { name: "Fri", value: 3 },
            { name: "Sat", value: 3 },
            { name: "Sun", value: 4 },
        ]
    },

    {
        label: "Avg Sell-through",
        value: "67.4%",
        sub: "across all stores",
        trend: "+2.1% this month",
        dir: "up",
        bad: false,
        color: "text-success",
        bg: "bg-success/10",
        clickable: true,
        history: [
            { name: "Mon", value: 65 },
            { name: "Tue", value: 61 },
            { name: "Wed", value: 63.2 },
            { name: "Thu", value: 61.8 },
            { name: "Fri", value: 64 },
            { name: "Sat", value: 65 },
            { name: "Sun", value: 67.1 },
        ]
    },
    {
        label: "Net Sales (Today)",
        value: "₹8.42L",
        sub: "across all channels",
        trend: "+12% vs yesterday",
        dir: "up",
        bad: false,
        color: "text-success",
        bg: "bg-success/10",
        clickable: true,
        history: [
            { name: "Mon", value: 6.2 },
            { name: "Tue", value: 7.5 },
            { name: "Wed", value: 6.8 },
            { name: "Thu", value: 7.1 },
            { name: "Fri", value: 8.0 },
            { name: "Sat", value: 8.2 },
            { name: "Sun", value: 8.42 },
        ]
    },
    {
        label: "On-Time Delivery",
        value: "78.5%",
        sub: "vendor performance",
        trend: "-2.4% vs last week",
        dir: "down",
        bad: true,
        color: "text-destructive",
        bg: "bg-destructive/10",
        clickable: false,
    },
    {
        label: "Fulfillment Rate",
        value: "82.4%",
        sub: "order completion",
        trend: "+1.2% improvement",
        dir: "up",
        bad: false,
        color: "text-success",
        bg: "bg-success/10",
        clickable: true,
        history: [
            { name: "Mon", value: 78 },
            { name: "Tue", value: 79 },
            { name: "Wed", value: 81 },
            { name: "Thu", value: 80 },
            { name: "Fri", value: 82 },
            { name: "Sat", value: 82 },
            { name: "Sun", value: 82.4 },
        ]
    },
];